name: 🤖 dep auto merge

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_REPO_TOKEN }}

      - uses: khulnasoft-lab/dependabot-auto-merge@main
        with:
          github-token: ${{ secrets.ORG_REPO_TOKEN }}
          target: all
