---
# This is a manually triggered workflow to build and publish the MkDocs from the
# main branch to GitHub pages at https://khulnasoft.github.io/kube-bench.
name: 🎉 Deploy documentation

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to be deployed
        required: true

jobs:
  deploy:
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - run: |
          pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material.git
          pip install mike
          pip install mkdocs-macros-plugin
        env:
          # Note: It is not the same as ${{ secrets.GITHUB_TOKEN }} !
          GH_TOKEN: ${{ secrets.ORG_REPO_TOKEN }}
      - run: |
          git config user.name "khulnasoft-bot"
          git config user.email "khulnasoft-bot@users.noreply.github.com"
      - run: |
          mike deploy --push --update-aliases ${{ github.event.inputs.version }} latest
